INSERT INTO products (name, description, price, stock, country, region, grape_variety, vintage, image_url) VALUES
('Château Margaux', '프랑스 보르도의 명품 와인', 180000, 10, 'France', 'Bordeaux', 'Cabernet Sauvignon', 2018, '/images/margaux.jpg'),
('Screaming Eagle', '나파 밸리의 전설적인 와인', 250000, 5, 'USA', 'Napa Valley', 'Cabernet Sauvignon', 2020, '/images/screaming-eagle.jpg'),
('Opus One', '나파 밸리의 프리미엄 와인', 350000, 8, 'USA', 'Napa Valley', 'Bordeaux Blend', 2019, '/images/opus-one.jpg'),
('Château Lafite Rothschild', '보르도의 대표적인 와인', 450000, 3, 'France', 'Pauillac', 'Cabernet Sauvignon', 2016, '/images/lafite.jpg'),
('Domaine de la Romanée-Conti', '부르고뉴의 최고급 와인', 550000, 2, 'France', 'Burgundy', 'Pinot Noir', 2018, '/images/drc.jpg'),
('Sassicaia', 'Top Super Tuscan wine', 280.00, 12, 'Italy', 'Tuscany', 'Cabernet Sauvignon', 2017, 'https://example.com/sassicaia.jpg'),
('Penfolds Grange', 'Iconic Australian Shiraz', 500.00, 5, 'Australia', 'Barossa Valley', 'Shiraz', 2016, 'https://example.com/penfolds.jpg'),
('Vega Sicilia Unico', 'Legendary Spanish red', 420.00, 6, 'Spain', 'Ribera del Duero', 'Tempranillo', 2012, 'https://example.com/vega.jpg'),
('Cloudy Bay Sauvignon Blanc', 'Crisp and refreshing white wine', 30.00, 25, 'New Zealand', 'Marlborough', 'Sauvignon Blanc', 2022, 'https://example.com/cloudybay.jpg'),
('Robert Mondavi Reserve', 'Classic Californian cabernet', 100.00, 14, 'USA', 'Napa Valley', 'Cabernet Sauvignon', 2019, 'https://example.com/mondavi.jpg'),
('Barolo Riserva', 'Bold and structured Italian red', 120.00, 9, 'Italy', 'Piedmont', 'Nebbiolo', 2014, 'https://example.com/barolo.jpg'),
('Chablis Premier Cru', 'Dry and mineral-rich white', 60.00, 18, 'France', 'Burgundy', 'Chardonnay', 2021, 'https://example.com/chablis.jpg'),
('Tokaji Aszú 5 Puttonyos', 'Hungarian dessert wine', 70.00, 7, 'Hungary', 'Tokaj', 'Furmint', 2010, 'https://example.com/tokaji.jpg'),
('Malbec Reserve', 'Rich and dark Argentine red', 35.00, 20, 'Argentina', 'Mendoza', 'Malbec', 2020, 'https://example.com/malbec.jpg'),
('Gewürztraminer Spätlese', 'Aromatic and semi-sweet white', 25.00, 15, 'Germany', 'Alsace', 'Gewürztraminer', 2021, 'https://example.com/gewurz.jpg'),
('Rioja Gran Reserva', 'Mature Spanish red', 85.00, 11, 'Spain', 'Rioja', 'Tempranillo', 2015, 'https://example.com/rioja.jpg'); 